language: node_js
node_js:
    #- "node" 
  - "7" 

#branches:
#  only:
#    - master

# Adding npm/node_modules
# and our build/ dir to cache
cache:
    directories:
        - node_modules
        - build

after_success:
  - chmod +x deploy.sh
  - './deploy.sh'
